---
title: 'R markdown: A tutorial'
author: "Paul Schneider & Sarah Bates"
date: "18/01/2022"
output: 'html_document'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Excercise 2


# Average Life expectancy

```{r, echo = F}

df_gapminder <- read.csv(file = "https://raw.githubusercontent.com/ScHARR-PHEDS/R4ScHARR/master/data/df_gapminder.csv")

# 1. Subset the data frame to a single year



# 2. Use a for loop to identify the mean life expectancy for each continent

# The function unique can be used to identify the unique value in a column
continents <- c(unique(df_2007$continent))

for (i in continents){
  
  
                                             
}

```


## Average GDP

```{r, echo=F, message=FALSE, warning = FALSE}


# 3. Create a custom function that present the mean GDP per capita for a certain continent and year.

f_gdpPercap <- function(continent, year){
  
  
    
}

# 4. Use this function to print the mean GDP for each continent in year you previously selected




```

## Maximum values

5. Add text that identifies the highest life expectancy and highest GDP per capita in the year you selected





